apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml
    path: nginx-helm
    repoURL: https://github.com/igagankalra/python-helloworld
    targetRevision: HEAD
  syncPolicy: {}
