namespace:
  name: demo

image:
  repository: nginx
  tag: alpine
  imagePullPolicy: IfNotPresent

resources:
  cpu: 50m
  memory: 256Mi

replicaCount: 3

service:
  port: 8111
  serviceType: ClusterIP

configMap:
  version: alpine