apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argocd 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nginx-manifests
    repoURL: https://github.com/igagankalra/python-helloworld
    targetRevision: HEAD
  syncPolicy: {}
