name: CI

on:
  workflow_run:
    workflows: ["Code Test"]
    types:
      - completed


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Loging to DockerHub
        uses: docker/login-action@v1
        with:
          username: igagankalra
          password: ${{ secrets.DOCKER_HUB_PERSONAL_ACCESS_TOKEN }}
      - 
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: igagankalra/gk-python-helloworld:latest